name = "astro-shadcn"
pages_build_output_dir = "dist"
compatibility_date = "2024-09-25"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSION"
id = "3c7a77f517f6434a9fea95a3fa5537c1"
